[package]
name = "kvs"
version = "0.1.0"
authors = ["Mat Wood <mat@thepacketgeek.com>"]
description = "A key-value store"
edition = "2018"


[[bin]]
name = "kvs"
test = false

[dependencies]
structopt = "0.3.14"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"